### ISSUE TITLE
Keeping the release versions in sync

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#449]
Example: releases show 1.0.5 https://github.com/newrelic/video-agent-roku/releases

Site shows 0.22.0 (bottom of the list): https://staging-opensource.newrelic.com/projects/newrelic/video-agent-roku

That looks like a bug.

**Comment by jbeveland27** [comment]
Good catch. The GraphQL query was pulling tag via the last entry alphabetically, rather than last commit date. Adjusted the query and ran sync-data job; this project and a few others are now fixed and list the latest release.

Closed by [https://github.com/newrelic/opensource-website/commit/33632f79b6b3000dbffd67a3be618b0cf7a43563](https://github.com/newrelic/opensource-website/commit/33632f79b6b3000dbffd67a3be618b0cf7a43563)

**Comment by jbeveland27** [comment]
Related: https://github.com/newrelic/opensource-website/commit/16e71626278f023e85085338c4b8bc78c4ffaa9e

Needed to build and commit the Action (dist/index.js) for it to run properly.
