### ISSUE TITLE
Responsive styles for markdown images

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#505]
See https://opensource.newrelic.com/contributing/ on mobile for an example.

@danielgolden can you review and decide if you want to work this or offer guidance for contributors.

**Comment by danielgolden** [comment]
I think this is a great first issue for contributors. I'll outline the issue in more details in this comment and then if it remains unaddressed for too long I'll carve out the time to take care of it myself.

---

[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
`<img />`'s provided via markdown are not being properly styled responsively. The images look more or less ok on desktop but once width of the viewport of the browser becomes lower than that of the image itself, then the image extends past the boundaries of the viewport. That is not desirable behavior.

[NOTE]: # ( Describe the problem you're encountering. )

## Steps to Reproduce
1. Visit https://opensource.newrelic.com/contributing/ on your phone _or_ visit [that same url](https://opensource.newrelic.com/contributing/) your desktop and reduce the width of your browser down to anything less that 480px.
2. Scroll down and look at the images on the page. Notice how much of them is hidden from your view because they don't resize with the browser window.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
It's expected that the images would fit inside of the viewport of the browser regardless of the viewport size.

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Browser name and version: Chrome 83.0.4103.116
* Operating System and version: MacOS Catalina 10.15.4
