### ISSUE TITLE
GitHub release only grabbed last conventional commit

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/opensource-website#526]
## Description

Recently had a PR merged that had a `chore` commit followed by a `fix` commit due to PR feedback. Only the `fix` commit made it into the release changelog, which was the least relevant of that batch of changes to share.

PR with multiple commits: See PR with multiple commits: https://github.com/newrelic/opensource-website/pull/523/commits

Resulting GitHub release: https://github.com/newrelic/opensource-website/releases/tag/v1.2.2

## Expected Behaviour

I'm guessing each conventional commit being represented would be the ideal? Or perhaps there's a different process expectation? As-is, we buried the important part of the PR which is not ideal.

**Comment by jpvajda** [comment]
I'm wondering if the proper thing to do is to keep the same convention as you work on a PR instead of intermingling `fixes` and `chores` or if you have to switch conventions, that's an entirely new PR.   the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/#specification) just says:

```
What do I do if the commit conforms to more than one of the commit types?

Go back and make multiple commits whenever possible. Part of the benefit of Conventional Commits is its ability to drive us to make more organized commits and PRs.
```
though it doesn't have an opinion on intermingling commit types.
