### ISSUE TITLE
Migrate OSS Site to Gatsby Cloud

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#757]
Once we've decided to move our Docs Site to Gatsby Cloud we'll want to move this site to Cloud.

### Acceptance Criteria 

- [x] setup webhook on repo 
- [x] Test build & deploy workflow 
- [x] Update architecture documentation
- [x] Update troubleshooting guide(s)
- [x] Commit updated documentation to repo

**Comment by nr-kkenney** [comment]
With the PR having an initial set of eyes and looking fine, im going to move this ticket to blocked since we said we didn't want to do DNS updates during the FS event.

also, idt we would disconnect this repo from amplify until later on, so that acceptance criteria can probably be removed to get this over the line.
